package proto;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

import event.Message;
import org.omg.CORBA.Any;
import tcp.buildMessage;

import java.util.LinkedList;
import java.util.List;
import java.util.Map;

public final class myMessage
{
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_request_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_request_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_feedback_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_feedback_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static
    {
        String[] descriptorData = {
                "\n\rMessage.proto\032\031google/protobuf/any.pro" +
                        "to\"F\n\007request\022\024\n\014functionName\030\001 \001(\t\022%\n\007d" +
                        "etails\030\002 \001(\0132\024.google.protobuf.Any\"j\n\010fe" +
                        "edback\022\024\n\014functionName\030\003 \001(\t\022\014\n\004mark\030\004 \001" +
                        "(\005\022\023\n\013backMessage\030\005 \001(\t\022%\n\007details\030\006 \003(\013" +
                        "2\024.google.protobuf.AnyB\013B\tmyMessageb\006pro" +
                        "to3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner()
                {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root)
                    {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                                com.google.protobuf.AnyProto.getDescriptor(),
                                }, assigner);
        internal_static_request_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_request_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_request_descriptor,
                new String[]{"FunctionName", "Details",});
        internal_static_feedback_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_feedback_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_feedback_descriptor,
                new String[]{"FunctionName", "Mark", "BackMessage", "Details",});
        com.google.protobuf.AnyProto.getDescriptor();
    }

    private myMessage()
    {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry)
    {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry)
    {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor()
    {
        return descriptor;
    }

    public interface requestOrBuilder extends
            // @@protoc_insertion_point(interface_extends:request)
            com.google.protobuf.MessageOrBuilder
    {

        /**
         * <code>string functionName = 1;</code>
         */
        String getFunctionName();

        /**
         * <code>string functionName = 1;</code>
         */
        com.google.protobuf.ByteString
        getFunctionNameBytes();

        /**
         * <code>.google.protobuf.Any details = 2;</code>
         */
        boolean hasDetails();

        /**
         * <code>.google.protobuf.Any details = 2;</code>
         */
        com.google.protobuf.Any getDetails();

        /**
         * <code>.google.protobuf.Any details = 2;</code>
         */
        com.google.protobuf.AnyOrBuilder getDetailsOrBuilder();
    }

    public interface feedbackOrBuilder extends
            // @@protoc_insertion_point(interface_extends:feedback)
            com.google.protobuf.MessageOrBuilder
    {

        /**
         * <code>string functionName = 3;</code>
         */
        String getFunctionName();

        /**
         * <code>string functionName = 3;</code>
         */
        com.google.protobuf.ByteString
        getFunctionNameBytes();

        /**
         * <code>int32 mark = 4;</code>
         */
        int getMark();

        /**
         * <code>string backMessage = 5;</code>
         */
        String getBackMessage();

        /**
         * <code>string backMessage = 5;</code>
         */
        com.google.protobuf.ByteString
        getBackMessageBytes();

        /**
         * <code>repeated .google.protobuf.Any details = 6;</code>
         */
        java.util.List<com.google.protobuf.Any>
        getDetailsList();

        /**
         * <code>repeated .google.protobuf.Any details = 6;</code>
         */
        com.google.protobuf.Any getDetails(int index);

        /**
         * <code>repeated .google.protobuf.Any details = 6;</code>
         */
        int getDetailsCount();

        /**
         * <code>repeated .google.protobuf.Any details = 6;</code>
         */
        java.util.List<? extends com.google.protobuf.AnyOrBuilder>
        getDetailsOrBuilderList();

        /**
         * <code>repeated .google.protobuf.Any details = 6;</code>
         */
        com.google.protobuf.AnyOrBuilder getDetailsOrBuilder(
                int index);
    }

    /**
     * Protobuf type {@code request}
     */
    public static final class request extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:request)
            requestOrBuilder
    {
        public static final int FUNCTIONNAME_FIELD_NUMBER = 1;
        public static final int DETAILS_FIELD_NUMBER = 2;
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:request)
        private static final myMessage.request DEFAULT_INSTANCE;
        private static final com.google.protobuf.Parser<request>
                PARSER = new com.google.protobuf.AbstractParser<request>()
        {
            public request parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException
            {
                return new request(input, extensionRegistry);
            }
        };

        static
        {
            DEFAULT_INSTANCE = new myMessage.request();
        }

        private volatile Object functionName_;
        private com.google.protobuf.Any details_;
        private byte memoizedIsInitialized = -1;

        // Use request.newBuilder() to construct.
        private request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder)
        {
            super(builder);
        }

        private request()
        {
            functionName_ = "";
        }

        private request(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException
        {
            this();
            if (extensionRegistry == null)
            {
                throw new NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try
            {
                boolean done = false;
                while (!done)
                {
                    int tag = input.readTag();
                    switch (tag)
                    {
                        case 0:
                            done = true;
                            break;
                        default:
                        {
                            if (!parseUnknownFieldProto3(
                                    input, unknownFields, extensionRegistry, tag))
                            {
                                done = true;
                            }
                            break;
                        }
                        case 10:
                        {
                            String s = input.readStringRequireUtf8();

                            functionName_ = s;
                            break;
                        }
                        case 18:
                        {
                            com.google.protobuf.Any.Builder subBuilder = null;
                            if (details_ != null)
                            {
                                subBuilder = details_.toBuilder();
                            }
                            details_ = input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry);
                            if (subBuilder != null)
                            {
                                subBuilder.mergeFrom(details_);
                                details_ = subBuilder.buildPartial();
                            }

                            break;
                        }
                    }
                }
            }
            catch (com.google.protobuf.InvalidProtocolBufferException e)
            {
                throw e.setUnfinishedMessage(this);
            }
            catch (java.io.IOException e)
            {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            }
            finally
            {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor()
        {
            return myMessage.internal_static_request_descriptor;
        }

        public static myMessage.request parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException
        {
            return PARSER.parseFrom(data);
        }

        public static myMessage.request parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException
        {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static myMessage.request parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException
        {
            return PARSER.parseFrom(data);
        }

        public static myMessage.request parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException
        {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static myMessage.request parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException
        {
            return PARSER.parseFrom(data);
        }

        public static myMessage.request parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException
        {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static myMessage.request parseFrom(java.io.InputStream input)
                throws java.io.IOException
        {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static myMessage.request parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException
        {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static myMessage.request parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException
        {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static myMessage.request parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException
        {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static myMessage.request parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException
        {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static myMessage.request parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException
        {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Builder newBuilder()
        {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(myMessage.request prototype)
        {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static myMessage.request getDefaultInstance()
        {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<request> parser()
        {
            return PARSER;
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields()
        {
            return this.unknownFields;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable()
        {
            return myMessage.internal_static_request_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            myMessage.request.class, myMessage.request.Builder.class);
        }

        /**
         * <code>string functionName = 1;</code>
         */
        public String getFunctionName()
        {
            Object ref = functionName_;
            if (ref instanceof String)
            {
                return (String) ref;
            }
            else
            {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                functionName_ = s;
                return s;
            }
        }

        /**
         * <code>string functionName = 1;</code>
         */
        public com.google.protobuf.ByteString
        getFunctionNameBytes()
        {
            Object ref = functionName_;
            if (ref instanceof String)
            {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                functionName_ = b;
                return b;
            }
            else
            {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>.google.protobuf.Any details = 2;</code>
         */
        public boolean hasDetails()
        {
            return details_ != null;
        }

        /**
         * <code>.google.protobuf.Any details = 2;</code>
         */
        public com.google.protobuf.Any getDetails()
        {
            return details_ == null ? com.google.protobuf.Any.getDefaultInstance() : details_;
        }

        /**
         * <code>.google.protobuf.Any details = 2;</code>
         */
        public com.google.protobuf.AnyOrBuilder getDetailsOrBuilder()
        {
            return getDetails();
        }

        public final boolean isInitialized()
        {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException
        {
            if (!getFunctionNameBytes().isEmpty())
            {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, functionName_);
            }
            if (details_ != null)
            {
                output.writeMessage(2, getDetails());
            }
            unknownFields.writeTo(output);
        }

        public int getSerializedSize()
        {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!getFunctionNameBytes().isEmpty())
            {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, functionName_);
            }
            if (details_ != null)
            {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(2, getDetails());
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @Override
        public boolean equals(final Object obj)
        {
            if (obj == this)
            {
                return true;
            }
            if (!(obj instanceof myMessage.request))
            {
                return super.equals(obj);
            }
            myMessage.request other = (myMessage.request) obj;

            boolean result = true;
            result = result && getFunctionName()
                    .equals(other.getFunctionName());
            result = result && (hasDetails() == other.hasDetails());
            if (hasDetails())
            {
                result = result && getDetails()
                        .equals(other.getDetails());
            }
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @Override
        public int hashCode()
        {
            if (memoizedHashCode != 0)
            {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + FUNCTIONNAME_FIELD_NUMBER;
            hash = (53 * hash) + getFunctionName().hashCode();
            if (hasDetails())
            {
                hash = (37 * hash) + DETAILS_FIELD_NUMBER;
                hash = (53 * hash) + getDetails().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public Builder newBuilderForType()
        {
            return newBuilder();
        }

        public Builder toBuilder()
        {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent)
        {
            Builder builder = new Builder(parent);
            return builder;
        }

        @Override
        public com.google.protobuf.Parser<request> getParserForType()
        {
            return PARSER;
        }

        public myMessage.request getDefaultInstanceForType()
        {
            return DEFAULT_INSTANCE;
        }

        /**
         * Protobuf type {@code request}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:request)
                myMessage.requestOrBuilder
        {
            private Object functionName_ = "";
            private com.google.protobuf.Any details_ = null;
            private com.google.protobuf.SingleFieldBuilderV3<
                    com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> detailsBuilder_;

            // Construct using myMessage.request.newBuilder()
            private Builder()
            {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent)
            {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor()
            {
                return myMessage.internal_static_request_descriptor;
            }

            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable()
            {
                return myMessage.internal_static_request_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                myMessage.request.class, myMessage.request.Builder.class);
            }

            private void maybeForceBuilderInitialization()
            {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders)
                {
                }
            }

            public Builder clear()
            {
                super.clear();
                functionName_ = "";

                if (detailsBuilder_ == null)
                {
                    details_ = null;
                }
                else
                {
                    details_ = null;
                    detailsBuilder_ = null;
                }
                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType()
            {
                return myMessage.internal_static_request_descriptor;
            }

            public myMessage.request getDefaultInstanceForType()
            {
                return myMessage.request.getDefaultInstance();
            }

            public myMessage.request build()
            {
                myMessage.request result = buildPartial();
                if (!result.isInitialized())
                {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public myMessage.request buildPartial()
            {
                myMessage.request result = new myMessage.request(this);
                result.functionName_ = functionName_;
                if (detailsBuilder_ == null)
                {
                    result.details_ = details_;
                }
                else
                {
                    result.details_ = detailsBuilder_.build();
                }
                onBuilt();
                return result;
            }

            public Builder clone()
            {
                return (Builder) super.clone();
            }

            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value)
            {
                return (Builder) super.setField(field, value);
            }

            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field)
            {
                return (Builder) super.clearField(field);
            }

            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof)
            {
                return (Builder) super.clearOneof(oneof);
            }

            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value)
            {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value)
            {
                return (Builder) super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other)
            {
                if (other instanceof myMessage.request)
                {
                    return mergeFrom((myMessage.request) other);
                }
                else
                {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(myMessage.request other)
            {
                if (other == myMessage.request.getDefaultInstance()) return this;
                if (!other.getFunctionName().isEmpty())
                {
                    functionName_ = other.functionName_;
                    onChanged();
                }
                if (other.hasDetails())
                {
                    mergeDetails(other.getDetails());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            public final boolean isInitialized()
            {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException
            {
                myMessage.request parsedMessage = null;
                try
                {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                }
                catch (com.google.protobuf.InvalidProtocolBufferException e)
                {
                    parsedMessage = (myMessage.request) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                }
                finally
                {
                    if (parsedMessage != null)
                    {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            /**
             * <code>string functionName = 1;</code>
             */
            public String getFunctionName()
            {
                Object ref = functionName_;
                if (!(ref instanceof String))
                {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    functionName_ = s;
                    return s;
                }
                else
                {
                    return (String) ref;
                }
            }

            /**
             * <code>string functionName = 1;</code>
             */
            public Builder setFunctionName(
                    String value)
            {
                if (value == null)
                {
                    throw new NullPointerException();
                }

                functionName_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string functionName = 1;</code>
             */
            public com.google.protobuf.ByteString
            getFunctionNameBytes()
            {
                Object ref = functionName_;
                if (ref instanceof String)
                {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    functionName_ = b;
                    return b;
                }
                else
                {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string functionName = 1;</code>
             */
            public Builder setFunctionNameBytes(
                    com.google.protobuf.ByteString value)
            {
                if (value == null)
                {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                functionName_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string functionName = 1;</code>
             */
            public Builder clearFunctionName()
            {

                functionName_ = getDefaultInstance().getFunctionName();
                onChanged();
                return this;
            }

            /**
             * <code>.google.protobuf.Any details = 2;</code>
             */
            public boolean hasDetails()
            {
                return detailsBuilder_ != null || details_ != null;
            }

            /**
             * <code>.google.protobuf.Any details = 2;</code>
             */
            public com.google.protobuf.Any getDetails()
            {
                if (detailsBuilder_ == null)
                {
                    return details_ == null ? com.google.protobuf.Any.getDefaultInstance() : details_;
                }
                else
                {
                    return detailsBuilder_.getMessage();
                }
            }

            /**
             * <code>.google.protobuf.Any details = 2;</code>
             */
            public Builder setDetails(com.google.protobuf.Any value)
            {
                if (detailsBuilder_ == null)
                {
                    if (value == null)
                    {
                        throw new NullPointerException();
                    }
                    details_ = value;
                    onChanged();
                }
                else
                {
                    detailsBuilder_.setMessage(value);
                }

                return this;
            }

            /**
             * <code>.google.protobuf.Any details = 2;</code>
             */
            public Builder setDetails(
                    com.google.protobuf.Any.Builder builderForValue)
            {
                if (detailsBuilder_ == null)
                {
                    details_ = builderForValue.build();
                    onChanged();
                }
                else
                {
                    detailsBuilder_.setMessage(builderForValue.build());
                }

                return this;
            }

            /**
             * <code>.google.protobuf.Any details = 2;</code>
             */
            public Builder mergeDetails(com.google.protobuf.Any value)
            {
                if (detailsBuilder_ == null)
                {
                    if (details_ != null)
                    {
                        details_ =
                                com.google.protobuf.Any.newBuilder(details_).mergeFrom(value).buildPartial();
                    }
                    else
                    {
                        details_ = value;
                    }
                    onChanged();
                }
                else
                {
                    detailsBuilder_.mergeFrom(value);
                }

                return this;
            }

            /**
             * <code>.google.protobuf.Any details = 2;</code>
             */
            public Builder clearDetails()
            {
                if (detailsBuilder_ == null)
                {
                    details_ = null;
                    onChanged();
                }
                else
                {
                    details_ = null;
                    detailsBuilder_ = null;
                }

                return this;
            }

            /**
             * <code>.google.protobuf.Any details = 2;</code>
             */
            public com.google.protobuf.Any.Builder getDetailsBuilder()
            {

                onChanged();
                return getDetailsFieldBuilder().getBuilder();
            }

            /**
             * <code>.google.protobuf.Any details = 2;</code>
             */
            public com.google.protobuf.AnyOrBuilder getDetailsOrBuilder()
            {
                if (detailsBuilder_ != null)
                {
                    return detailsBuilder_.getMessageOrBuilder();
                }
                else
                {
                    return details_ == null ?
                            com.google.protobuf.Any.getDefaultInstance() : details_;
                }
            }

            /**
             * <code>.google.protobuf.Any details = 2;</code>
             */
            private com.google.protobuf.SingleFieldBuilderV3<
                    com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>
            getDetailsFieldBuilder()
            {
                if (detailsBuilder_ == null)
                {
                    detailsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                            com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                            getDetails(),
                            getParentForChildren(),
                            isClean());
                    details_ = null;
                }
                return detailsBuilder_;
            }

            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields)
            {
                return super.setUnknownFieldsProto3(unknownFields);
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields)
            {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:request)
        }

    }

    /**
     * Protobuf type {@code feedback}
     */
    public static final class feedback extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:feedback)
            feedbackOrBuilder , Message
    {
        public static final int FUNCTIONNAME_FIELD_NUMBER = 3;
        public static final int MARK_FIELD_NUMBER = 4;
        public static final int BACKMESSAGE_FIELD_NUMBER = 5;
        public static final int DETAILS_FIELD_NUMBER = 6;
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:feedback)
        private static final myMessage.feedback DEFAULT_INSTANCE;
        private static final com.google.protobuf.Parser<feedback>
                PARSER = new com.google.protobuf.AbstractParser<feedback>()
        {
            public feedback parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException
            {
                return new feedback(input, extensionRegistry);
            }
        };

        static
        {
            DEFAULT_INSTANCE = new myMessage.feedback();
        }

        private int bitField0_;
        private volatile Object functionName_;
        private int mark_;
        private volatile Object backMessage_;
        private java.util.List<com.google.protobuf.Any> details_;
        private byte memoizedIsInitialized = -1;

        // Use feedback.newBuilder() to construct.
        private feedback(com.google.protobuf.GeneratedMessageV3.Builder<?> builder)
        {
            super(builder);
        }

        private feedback()
        {
            functionName_ = "";
            mark_ = 0;
            backMessage_ = "";
            details_ = java.util.Collections.emptyList();
        }

        private feedback(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException
        {
            this();
            if (extensionRegistry == null)
            {
                throw new NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try
            {
                boolean done = false;
                while (!done)
                {
                    int tag = input.readTag();
                    switch (tag)
                    {
                        case 0:
                            done = true;
                            break;
                        default:
                        {
                            if (!parseUnknownFieldProto3(
                                    input, unknownFields, extensionRegistry, tag))
                            {
                                done = true;
                            }
                            break;
                        }
                        case 26:
                        {
                            String s = input.readStringRequireUtf8();

                            functionName_ = s;
                            break;
                        }
                        case 32:
                        {

                            mark_ = input.readInt32();
                            break;
                        }
                        case 42:
                        {
                            String s = input.readStringRequireUtf8();

                            backMessage_ = s;
                            break;
                        }
                        case 50:
                        {
                            if (!((mutable_bitField0_ & 0x00000008) == 0x00000008))
                            {
                                details_ = new java.util.ArrayList<com.google.protobuf.Any>();
                                mutable_bitField0_ |= 0x00000008;
                            }
                            details_.add(
                                    input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry));
                            break;
                        }
                    }
                }
            }
            catch (com.google.protobuf.InvalidProtocolBufferException e)
            {
                throw e.setUnfinishedMessage(this);
            }
            catch (java.io.IOException e)
            {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            }
            finally
            {
                if (((mutable_bitField0_ & 0x00000008) == 0x00000008))
                {
                    details_ = java.util.Collections.unmodifiableList(details_);
                }
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor()
        {
            return myMessage.internal_static_feedback_descriptor;
        }




        public static myMessage.feedback parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException
        {
            return PARSER.parseFrom(data);
        }

        public static myMessage.feedback parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException
        {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static myMessage.feedback parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException
        {
            return PARSER.parseFrom(data);
        }

        public static myMessage.feedback parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException
        {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static myMessage.feedback parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException
        {
            return PARSER.parseFrom(data);
        }

        public static myMessage.feedback parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException
        {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static myMessage.feedback parseFrom(java.io.InputStream input)
                throws java.io.IOException
        {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static myMessage.feedback parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException
        {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static myMessage.feedback parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException
        {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static myMessage.feedback parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException
        {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static myMessage.feedback parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException
        {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static myMessage.feedback parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException
        {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Builder newBuilder()
        {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(myMessage.feedback prototype)
        {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static myMessage.feedback getDefaultInstance()
        {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<feedback> parser()
        {
            return PARSER;
        }


        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields()
        {
            return this.unknownFields;
        }


        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable()
        {
            return myMessage.internal_static_feedback_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            myMessage.feedback.class, myMessage.feedback.Builder.class);
        }

        /**
         * <code>string functionName = 3;</code>
         */
        public String getFunctionName()
        {
            Object ref = functionName_;
            if (ref instanceof String)
            {
                return (String) ref;
            }
            else
            {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                functionName_ = s;
                return s;
            }
        }

        /**
         * <code>string functionName = 3;</code>
         */
        public com.google.protobuf.ByteString
        getFunctionNameBytes()
        {
            Object ref = functionName_;
            if (ref instanceof String)
            {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                functionName_ = b;
                return b;
            }
            else
            {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>int32 mark = 4;</code>
         */
        public int getMark()
        {
            return mark_;
        }

        /**
         * <code>string backMessage = 5;</code>
         */
        public String getBackMessage()
        {
            Object ref = backMessage_;
            if (ref instanceof String)
            {
                return (String) ref;
            }
            else
            {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                backMessage_ = s;
                return s;
            }
        }

        public List<Map<String,Object>> getOutData()
        {
            java.util.List<com.google.protobuf.Any> anyList = getDetailsList();
            List<Map<String,Object>> mapList = new LinkedList<>();
            for(com.google.protobuf.Any any : anyList)
            {
                mapList.add(buildMessage.AnyToMap(any));
            }
            return mapList;
        }


        /**
         * <code>string backMessage = 5;</code>
         */
        public com.google.protobuf.ByteString
        getBackMessageBytes()
        {
            Object ref = backMessage_;
            if (ref instanceof String)
            {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                backMessage_ = b;
                return b;
            }
            else
            {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>repeated .google.protobuf.Any details = 6;</code>
         */
        public java.util.List<com.google.protobuf.Any> getDetailsList()
        {
            return details_;
        }

        /**
         * <code>repeated .google.protobuf.Any details = 6;</code>
         */
        public java.util.List<? extends com.google.protobuf.AnyOrBuilder>
        getDetailsOrBuilderList()
        {
            return details_;
        }

        /**
         * <code>repeated .google.protobuf.Any details = 6;</code>
         */
        public int getDetailsCount()
        {
            return details_.size();
        }

        /**
         * <code>repeated .google.protobuf.Any details = 6;</code>
         */
        public com.google.protobuf.Any getDetails(int index)
        {
            return details_.get(index);
        }

        /**
         * <code>repeated .google.protobuf.Any details = 6;</code>
         */
        public com.google.protobuf.AnyOrBuilder getDetailsOrBuilder(
                int index)
        {
            return details_.get(index);
        }

        public final boolean isInitialized()
        {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException
        {
            if (!getFunctionNameBytes().isEmpty())
            {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 3, functionName_);
            }
            if (mark_ != 0)
            {
                output.writeInt32(4, mark_);
            }
            if (!getBackMessageBytes().isEmpty())
            {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 5, backMessage_);
            }
            for (int i = 0; i < details_.size(); i++)
            {
                output.writeMessage(6, details_.get(i));
            }
            unknownFields.writeTo(output);
        }

        public int getSerializedSize()
        {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!getFunctionNameBytes().isEmpty())
            {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, functionName_);
            }
            if (mark_ != 0)
            {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(4, mark_);
            }
            if (!getBackMessageBytes().isEmpty())
            {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, backMessage_);
            }
            for (int i = 0; i < details_.size(); i++)
            {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(6, details_.get(i));
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @Override
        public boolean equals(final Object obj)
        {
            if (obj == this)
            {
                return true;
            }
            if (!(obj instanceof myMessage.feedback))
            {
                return super.equals(obj);
            }
            myMessage.feedback other = (myMessage.feedback) obj;

            boolean result = true;
            result = result && getFunctionName()
                    .equals(other.getFunctionName());
            result = result && (getMark()
                    == other.getMark());
            result = result && getBackMessage()
                    .equals(other.getBackMessage());
            result = result && getDetailsList()
                    .equals(other.getDetailsList());
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @Override
        public int hashCode()
        {
            if (memoizedHashCode != 0)
            {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + FUNCTIONNAME_FIELD_NUMBER;
            hash = (53 * hash) + getFunctionName().hashCode();
            hash = (37 * hash) + MARK_FIELD_NUMBER;
            hash = (53 * hash) + getMark();
            hash = (37 * hash) + BACKMESSAGE_FIELD_NUMBER;
            hash = (53 * hash) + getBackMessage().hashCode();
            if (getDetailsCount() > 0)
            {
                hash = (37 * hash) + DETAILS_FIELD_NUMBER;
                hash = (53 * hash) + getDetailsList().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public Builder newBuilderForType()
        {
            return newBuilder();
        }

        public Builder toBuilder()
        {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent)
        {
            Builder builder = new Builder(parent);
            return builder;
        }

        @Override
        public com.google.protobuf.Parser<feedback> getParserForType()
        {
            return PARSER;
        }

        public myMessage.feedback getDefaultInstanceForType()
        {
            return DEFAULT_INSTANCE;
        }

        /**
         * Protobuf type {@code feedback}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:feedback)
                myMessage.feedbackOrBuilder
        {
            private int bitField0_;
            private Object functionName_ = "";
            private int mark_;
            private Object backMessage_ = "";
            private java.util.List<com.google.protobuf.Any> details_ =
                    java.util.Collections.emptyList();
            private com.google.protobuf.RepeatedFieldBuilderV3<
                    com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> detailsBuilder_;

            // Construct using myMessage.feedback.newBuilder()
            private Builder()
            {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent)
            {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor()
            {
                return myMessage.internal_static_feedback_descriptor;
            }

            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable()
            {
                return myMessage.internal_static_feedback_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                myMessage.feedback.class, myMessage.feedback.Builder.class);
            }

            private void maybeForceBuilderInitialization()
            {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders)
                {
                    getDetailsFieldBuilder();
                }
            }

            public Builder clear()
            {
                super.clear();
                functionName_ = "";

                mark_ = 0;

                backMessage_ = "";

                if (detailsBuilder_ == null)
                {
                    details_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000008);
                }
                else
                {
                    detailsBuilder_.clear();
                }
                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType()
            {
                return myMessage.internal_static_feedback_descriptor;
            }

            public myMessage.feedback getDefaultInstanceForType()
            {
                return myMessage.feedback.getDefaultInstance();
            }

            public myMessage.feedback build()
            {
                myMessage.feedback result = buildPartial();
                if (!result.isInitialized())
                {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public myMessage.feedback buildPartial()
            {
                myMessage.feedback result = new myMessage.feedback(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                result.functionName_ = functionName_;
                result.mark_ = mark_;
                result.backMessage_ = backMessage_;
                if (detailsBuilder_ == null)
                {
                    if (((bitField0_ & 0x00000008) == 0x00000008))
                    {
                        details_ = java.util.Collections.unmodifiableList(details_);
                        bitField0_ = (bitField0_ & ~0x00000008);
                    }
                    result.details_ = details_;
                }
                else
                {
                    result.details_ = detailsBuilder_.build();
                }
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder clone()
            {
                return (Builder) super.clone();
            }

            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value)
            {
                return (Builder) super.setField(field, value);
            }

            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field)
            {
                return (Builder) super.clearField(field);
            }

            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof)
            {
                return (Builder) super.clearOneof(oneof);
            }

            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value)
            {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value)
            {
                return (Builder) super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other)
            {
                if (other instanceof myMessage.feedback)
                {
                    return mergeFrom((myMessage.feedback) other);
                }
                else
                {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(myMessage.feedback other)
            {
                if (other == myMessage.feedback.getDefaultInstance()) return this;
                if (!other.getFunctionName().isEmpty())
                {
                    functionName_ = other.functionName_;
                    onChanged();
                }
                if (other.getMark() != 0)
                {
                    setMark(other.getMark());
                }
                if (!other.getBackMessage().isEmpty())
                {
                    backMessage_ = other.backMessage_;
                    onChanged();
                }
                if (detailsBuilder_ == null)
                {
                    if (!other.details_.isEmpty())
                    {
                        if (details_.isEmpty())
                        {
                            details_ = other.details_;
                            bitField0_ = (bitField0_ & ~0x00000008);
                        }
                        else
                        {
                            ensureDetailsIsMutable();
                            details_.addAll(other.details_);
                        }
                        onChanged();
                    }
                }
                else
                {
                    if (!other.details_.isEmpty())
                    {
                        if (detailsBuilder_.isEmpty())
                        {
                            detailsBuilder_.dispose();
                            detailsBuilder_ = null;
                            details_ = other.details_;
                            bitField0_ = (bitField0_ & ~0x00000008);
                            detailsBuilder_ =
                                    com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                                            getDetailsFieldBuilder() : null;
                        }
                        else
                        {
                            detailsBuilder_.addAllMessages(other.details_);
                        }
                    }
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            public final boolean isInitialized()
            {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException
            {
                myMessage.feedback parsedMessage = null;
                try
                {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                }
                catch (com.google.protobuf.InvalidProtocolBufferException e)
                {
                    parsedMessage = (myMessage.feedback) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                }
                finally
                {
                    if (parsedMessage != null)
                    {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            /**
             * <code>string functionName = 3;</code>
             */
            public String getFunctionName()
            {
                Object ref = functionName_;
                if (!(ref instanceof String))
                {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    functionName_ = s;
                    return s;
                }
                else
                {
                    return (String) ref;
                }
            }

            /**
             * <code>string functionName = 3;</code>
             */
            public Builder setFunctionName(
                    String value)
            {
                if (value == null)
                {
                    throw new NullPointerException();
                }

                functionName_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string functionName = 3;</code>
             */
            public com.google.protobuf.ByteString
            getFunctionNameBytes()
            {
                Object ref = functionName_;
                if (ref instanceof String)
                {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    functionName_ = b;
                    return b;
                }
                else
                {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string functionName = 3;</code>
             */
            public Builder setFunctionNameBytes(
                    com.google.protobuf.ByteString value)
            {
                if (value == null)
                {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                functionName_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string functionName = 3;</code>
             */
            public Builder clearFunctionName()
            {

                functionName_ = getDefaultInstance().getFunctionName();
                onChanged();
                return this;
            }

            /**
             * <code>int32 mark = 4;</code>
             */
            public int getMark()
            {
                return mark_;
            }

            /**
             * <code>int32 mark = 4;</code>
             */
            public Builder setMark(int value)
            {

                mark_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>int32 mark = 4;</code>
             */
            public Builder clearMark()
            {

                mark_ = 0;
                onChanged();
                return this;
            }

            /**
             * <code>string backMessage = 5;</code>
             */
            public String getBackMessage()
            {
                Object ref = backMessage_;
                if (!(ref instanceof String))
                {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    backMessage_ = s;
                    return s;
                }
                else
                {
                    return (String) ref;
                }
            }

            /**
             * <code>string backMessage = 5;</code>
             */
            public Builder setBackMessage(
                    String value)
            {
                if (value == null)
                {
                    throw new NullPointerException();
                }

                backMessage_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string backMessage = 5;</code>
             */
            public com.google.protobuf.ByteString
            getBackMessageBytes()
            {
                Object ref = backMessage_;
                if (ref instanceof String)
                {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    backMessage_ = b;
                    return b;
                }
                else
                {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string backMessage = 5;</code>
             */
            public Builder setBackMessageBytes(
                    com.google.protobuf.ByteString value)
            {
                if (value == null)
                {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                backMessage_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string backMessage = 5;</code>
             */
            public Builder clearBackMessage()
            {

                backMessage_ = getDefaultInstance().getBackMessage();
                onChanged();
                return this;
            }

            private void ensureDetailsIsMutable()
            {
                if (!((bitField0_ & 0x00000008) == 0x00000008))
                {
                    details_ = new java.util.ArrayList<com.google.protobuf.Any>(details_);
                    bitField0_ |= 0x00000008;
                }
            }

            /**
             * <code>repeated .google.protobuf.Any details = 6;</code>
             */
            public java.util.List<com.google.protobuf.Any> getDetailsList()
            {
                if (detailsBuilder_ == null)
                {
                    return java.util.Collections.unmodifiableList(details_);
                }
                else
                {
                    return detailsBuilder_.getMessageList();
                }
            }

            /**
             * <code>repeated .google.protobuf.Any details = 6;</code>
             */
            public int getDetailsCount()
            {
                if (detailsBuilder_ == null)
                {
                    return details_.size();
                }
                else
                {
                    return detailsBuilder_.getCount();
                }
            }

            /**
             * <code>repeated .google.protobuf.Any details = 6;</code>
             */
            public com.google.protobuf.Any getDetails(int index)
            {
                if (detailsBuilder_ == null)
                {
                    return details_.get(index);
                }
                else
                {
                    return detailsBuilder_.getMessage(index);
                }
            }

            /**
             * <code>repeated .google.protobuf.Any details = 6;</code>
             */
            public Builder setDetails(
                    int index, com.google.protobuf.Any value)
            {
                if (detailsBuilder_ == null)
                {
                    if (value == null)
                    {
                        throw new NullPointerException();
                    }
                    ensureDetailsIsMutable();
                    details_.set(index, value);
                    onChanged();
                }
                else
                {
                    detailsBuilder_.setMessage(index, value);
                }
                return this;
            }

            /**
             * <code>repeated .google.protobuf.Any details = 6;</code>
             */
            public Builder setDetails(
                    int index, com.google.protobuf.Any.Builder builderForValue)
            {
                if (detailsBuilder_ == null)
                {
                    ensureDetailsIsMutable();
                    details_.set(index, builderForValue.build());
                    onChanged();
                }
                else
                {
                    detailsBuilder_.setMessage(index, builderForValue.build());
                }
                return this;
            }

            /**
             * <code>repeated .google.protobuf.Any details = 6;</code>
             */
            public Builder addDetails(com.google.protobuf.Any value)
            {
                if (detailsBuilder_ == null)
                {
                    if (value == null)
                    {
                        throw new NullPointerException();
                    }
                    ensureDetailsIsMutable();
                    details_.add(value);
                    onChanged();
                }
                else
                {
                    detailsBuilder_.addMessage(value);
                }
                return this;
            }

            /**
             * <code>repeated .google.protobuf.Any details = 6;</code>
             */
            public Builder addDetails(
                    int index, com.google.protobuf.Any value)
            {
                if (detailsBuilder_ == null)
                {
                    if (value == null)
                    {
                        throw new NullPointerException();
                    }
                    ensureDetailsIsMutable();
                    details_.add(index, value);
                    onChanged();
                }
                else
                {
                    detailsBuilder_.addMessage(index, value);
                }
                return this;
            }

            /**
             * <code>repeated .google.protobuf.Any details = 6;</code>
             */
            public Builder addDetails(
                    com.google.protobuf.Any.Builder builderForValue)
            {
                if (detailsBuilder_ == null)
                {
                    ensureDetailsIsMutable();
                    details_.add(builderForValue.build());
                    onChanged();
                }
                else
                {
                    detailsBuilder_.addMessage(builderForValue.build());
                }
                return this;
            }

            /**
             * <code>repeated .google.protobuf.Any details = 6;</code>
             */
            public Builder addDetails(
                    int index, com.google.protobuf.Any.Builder builderForValue)
            {
                if (detailsBuilder_ == null)
                {
                    ensureDetailsIsMutable();
                    details_.add(index, builderForValue.build());
                    onChanged();
                }
                else
                {
                    detailsBuilder_.addMessage(index, builderForValue.build());
                }
                return this;
            }

            /**
             * <code>repeated .google.protobuf.Any details = 6;</code>
             */
            public Builder addAllDetails(
                    Iterable<? extends com.google.protobuf.Any> values)
            {
                if (detailsBuilder_ == null)
                {
                    ensureDetailsIsMutable();
                    com.google.protobuf.AbstractMessageLite.Builder.addAll(
                            values, details_);
                    onChanged();
                }
                else
                {
                    detailsBuilder_.addAllMessages(values);
                }
                return this;
            }

            /**
             * <code>repeated .google.protobuf.Any details = 6;</code>
             */
            public Builder clearDetails()
            {
                if (detailsBuilder_ == null)
                {
                    details_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000008);
                    onChanged();
                }
                else
                {
                    detailsBuilder_.clear();
                }
                return this;
            }

            /**
             * <code>repeated .google.protobuf.Any details = 6;</code>
             */
            public Builder removeDetails(int index)
            {
                if (detailsBuilder_ == null)
                {
                    ensureDetailsIsMutable();
                    details_.remove(index);
                    onChanged();
                }
                else
                {
                    detailsBuilder_.remove(index);
                }
                return this;
            }

            /**
             * <code>repeated .google.protobuf.Any details = 6;</code>
             */
            public com.google.protobuf.Any.Builder getDetailsBuilder(
                    int index)
            {
                return getDetailsFieldBuilder().getBuilder(index);
            }

            /**
             * <code>repeated .google.protobuf.Any details = 6;</code>
             */
            public com.google.protobuf.AnyOrBuilder getDetailsOrBuilder(
                    int index)
            {
                if (detailsBuilder_ == null)
                {
                    return details_.get(index);
                }
                else
                {
                    return detailsBuilder_.getMessageOrBuilder(index);
                }
            }

            /**
             * <code>repeated .google.protobuf.Any details = 6;</code>
             */
            public java.util.List<? extends com.google.protobuf.AnyOrBuilder>
            getDetailsOrBuilderList()
            {
                if (detailsBuilder_ != null)
                {
                    return detailsBuilder_.getMessageOrBuilderList();
                }
                else
                {
                    return java.util.Collections.unmodifiableList(details_);
                }
            }

            /**
             * <code>repeated .google.protobuf.Any details = 6;</code>
             */
            public com.google.protobuf.Any.Builder addDetailsBuilder()
            {
                return getDetailsFieldBuilder().addBuilder(
                        com.google.protobuf.Any.getDefaultInstance());
            }

            /**
             * <code>repeated .google.protobuf.Any details = 6;</code>
             */
            public com.google.protobuf.Any.Builder addDetailsBuilder(
                    int index)
            {
                return getDetailsFieldBuilder().addBuilder(
                        index, com.google.protobuf.Any.getDefaultInstance());
            }

            /**
             * <code>repeated .google.protobuf.Any details = 6;</code>
             */
            public java.util.List<com.google.protobuf.Any.Builder>
            getDetailsBuilderList()
            {
                return getDetailsFieldBuilder().getBuilderList();
            }

            private com.google.protobuf.RepeatedFieldBuilderV3<
                    com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>
            getDetailsFieldBuilder()
            {
                if (detailsBuilder_ == null)
                {
                    detailsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                            com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                            details_,
                            ((bitField0_ & 0x00000008) == 0x00000008),
                            getParentForChildren(),
                            isClean());
                    details_ = null;
                }
                return detailsBuilder_;
            }

            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields)
            {
                return super.setUnknownFieldsProto3(unknownFields);
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields)
            {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:feedback)
        }

    }

    // @@protoc_insertion_point(outer_class_scope)
}
